language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
before_install:
- chmod +x mvnw
script:
- "./mvnw clean"
- "./mvnw package -DskipTests"
branches:
  only:
  - master
deploy:
  provider: heroku
  app: travis-heroku
  skip_cleanup: true
  api_key:
    secure: qPcHc/0BigDFKqEF2mQLoVJ80q7xqHKwURqr4cNf1yWGSe8jVqRYK6Uxbqm3vS0qhoULkJdnw8pz8Hk/C5bPg7gyfUoqX+hYu8P5dbzHDmLYOAiLFIdcfJwdWdhB6JA5Q6WljAmOGJhGbPB/p82rRUHgPzU7mJgXJMl5VrFDt0uPA12YaP8dAi/3jiAumKibQEo7voPcPDpRMkc7qWbw21ttpa/MC0jy8rUg0RL7uEL2rPEVp2Cp+Pbu6JD3JbqgfIkTrZ/RbZJv4Y8b3THDD7Bu0W5YHsaAx5GwRN6FTsttBnSUjHT6EkM5fJ5w3U2a6ptVBsZOHR7yGFieJLQhN84xorUFdt/tMitYfIGQZ0i+pjzLXEJpJZYL4LE7TjZ6Yh32N/bYDkvWrpRUAIF0VtOlBsFFqnlaB8+xMGKn967gP2WrrUIbLZaPNbNgAsVzkcjszJ2BerlPugF7LSRqYQEnmttYN4cOtfO9XLl+iUZOBaEaxRY+9Xz1mzW3Lchn6HZHDLphyzr2lr/uWNoP2RX6FPUg+K048s44B7Xlc33E+vS7qoIXU2lyZWJYbFRfTdNnOnZ8Ug/eQOyIq7A+Q/49nRx3TXj94jZd5PigPJlUjkbB6SGf3q00DEd4M+N6t8Ut6+KeKJ9TyW0sJh/lGvWhnNvUgKx6vOqwadlZJxs=
