language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
before_install:
- chmod +x mvnw
script:
- "./mvnw clean"
- "./mvnw package -DskipTests"
branches:
  only:
  - master
deploy:
  provider: heroku
  app: travis-heroku
  skip_cleanup: true
  api_key:
    secure: "oH4lMcC9e7O5FvFFCtU2hhR5lhi8lPPJl8S+ojZWqHIU25ne8q29Seh6NahGU8Wmq5TPMXiL6TskIlmL136idbDmAWZd47/jkcmGyQkjISQnLq6TalYjL9jr3/ryEgEND/pC++etB/wXALw/Dr9AQ0A80awqck0MK2NcuN1RnOxMYxhgNJvYTeE9OVeO7GfPyWYtnlJLxqUz3pFm+j9afR2iAvglrxuLtTUhSp29gtoNwLvwx8viYHCtZH0ODktWWXDO29Cji0p+8FP1fToIr0vqY3UeAl7HiFmNrsj2qQD+hsZRGrmIKNr/fU7Nli7aOMnuZ3koXw5hIvht/fcPnNARjCLxLm/Vpy8sb67pdjGBJ204Djby1DGc7nI3LWf5kkFC//UF1taRyzITc8meRopsnA5BYhBDq0TQJSf/XpJOmhLpbl+S6hP/6/MDL2J2GFKdZSREUnR7M+J48nOm3jVusAhBV/FdT5uPLBgEB8VhLOAaHMPFgXGp2Qr81GfZw4yU6lwii81y7V26TahhXgL84k0j6eZCOpR7cIfxiR/GjNFRmspFijVsCQEJS++iaG33tfJKg7V61+XzZahmAr30Jxt2cjlTvQq6Ngadgg/Obp5Pey1alXXH8pXbhuCR1TVNJH35nvr0ziPOGs95MWdIHH1xvaVzqRv1EDogsyA="
