language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - ./mvnw clean
  - ./mvnw test
  - ./mvnw package -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
