language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
before_install:
  - chmod +x mvnw
script:
  - ./mvnw clean
#  - ./mvnw test
  - ./mvnw package -DskipTests
branches:
  only:
  - master
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
deploy:
  provider: heroku
  app: cadsoft
  skip_cleanup: true
  api_key:
    secure: "JQI2Sh2i5zd6D145GO0LV16MgY+DDzh8Xxh8ZOuGEloTKBu3j5bHfJN8O2MRHdzYmjUPl3x4jJuCTSJxtLB3AFEHb83XKvyRueQmDyYq9lmR5qSdw58dp0rE8YwAv+yd+GiVtsikrUV6SjEx4QGoNqk96Xuc7IBgqfS/MGO7umrOayRsrS8WIuy6w1fZTsCfYkIxfghGHoCSMMHNEGlEdwrvPLQXjpmSXcDGJirpCE5hC8glpuvK3LYMmxpP27WYeWvIuc3LFXTmpw/lIzf8XADUzpe+pzOx0ZPUqPngJGfsamjp5D+1dz3OGSq6JSOgb+y9Lr+AfH5x3Jo6AFWUnv3xtDF7lBEke4BloE15yuSAHC6Du5v3HwDfBT3NKYMC3S/rW4mS47BdUJxk2eFXae48L8MIzpHBIbZcMkSy6A7pX/lkK/TPDugExOBlkz4tqWu7vPppelcgylDUaJEaTTEyTCCnSO6Lt8G6DRE1oIvun7mLs4uXKwF9+Mar7N0gf8dZ2s3wXOJi2zCOfXpMDzvNlT+nNnMw49WQb5obpiLWz1LB0Sn4EmaGhgQTUP5rbq4B/cAhD+vk4TgyfioErmMSQZT8kUCWWBhU2/h6MM9FpJdtqkwsL3pF5W2A0vMvNsVBx7D+Pkp4INVN+Lqj88bWSiI/cZUg1MHsltEmsSQ="
