language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
before_install:
- chmod +x mvnw
script:
- "./mvnw clean"
- "./mvnw package"
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: Byc3LcgbmLe04M3nXV8jeE60fso1B+vz+l3pZmR9j3Lr8eqfR/h90LCoH4NZkfn8JYm8/PrlDTeZKUCkfW2PgoWJ5eSPpYJnsSh1ihCs2KT3AB5BLArifVnv9R423Lm/gh/vtc1L9EAjew8xTCUlbFO+oQLv6BJCWJ6rwvovatElv0US68wF7nRmR+Upys7YIvMQ00su7BkA8ovH1f32CUIrv6i/fN5mKwvHyOJJK1b45JX30hF6BZuVFsTTCRwKY0vEuEMB4CwvJ3KXDzH7es3Oiq959O8dpqXL6u2QbUcyi2gza+c/wI01qhy1aE2hsxItZ0nSl5VBmrTgUHi/NGP1W1s+DMs55nX2QHVElZLecWOKkFrYdaIGn2wJRJjpdBL08HRu62RcZ+IOgznD7EbjEn+IXob+E7t2oNF1s0JPob/+TJnJ0DaiHYh0Ds4jzkwl+lR72lBmkCTB0NGoS+8g27ODHvpxK54yoDlhFE+mw1kYBbAsqAIWcoeiC2ByBlWFcLFnWKNEsEto57uV6PbHsMxQKEt/jKWruh7rNlYxyLi2B99T7p0QmTxOO9kkhj7YmQDvktqNHSyaNXGaR1vuvK1KuisejBoo47jUhPqYSeHrs0sA+62S2XZCb5y9/SJUjtYnPcYKsl1Po03dlKv3dvZ2tzS+gmphy8hxdWo=
  app: travis-heroku
  skip_cleanup: true
  on:
    repo: dmkach/TravisHerokuDemo
